otelAgent:
  config:
    receivers:
      receiver_creator:
        receivers:
          smartagent/mongodb:
            rule: type == "pod" && name matches "mongo"
            config:
              type: collectd/mongodb
              host: mongodb.default.svc.cluster.local
              port: 27017
              databases: ["admin", "O11y", "local", "config"]
              sendCollectionMetrics: true
              sendCollectionTopMetrics: true
