otelAgent:
  config:
    receivers:
      receiver_creator:
        receivers:
          smartagent/zookeeper:
            rule: type == "pod" && name matches "kafka-zookeeper"
            config:
              type: collectd/zookeeper
              host: kafka-zookeeper
              port: 2181
